### PR TITLE
Update test spec as per tdl client jave changes

### PR DESCRIPTION
**Pull request by neomatrix369**
* Updating test spec from client-spec
* set all terms referring to `tdl-client` to `tdl-client-nodejs`
* Removed ClientAction implementation from all across implementation and test code
* Rename then() to build() in ProcessingRules.java
* Some refactorings to prepare injecting queue names via constructor
* Update implementation to work with the latest version of the Spec

--- 

One question when looking at this PR, why don't we use one tdl-client-xxxx i.e. `tdl-client-java` when dealing with JMS  or even for SQS, rather than a separate one per language, there is nothing language or platform specific about the communication between the client and server. 

Something of this sort can bring down maintenance many folds

### CODE REVIEW

**Comment by neomatrix369** [comment]
If it looks good please merge, lets keep PRs small

**Comment by neomatrix369** [comment]
Please have a quick look at package-lock.json to see if you are happy with it

**Comment by neomatrix369** [comment]
Let's discuss this PR - there might be missing parts here.

**Comment by neomatrix369** [comment]
It seems there aren't enough tests that fulfill coverage

**Comment by neomatrix369** [comment]
I have left some TODOs for discussions during PR

**Comment by neomatrix369** [comment]
The nodejs test runner isn't telling using that there are missing tests / 'then' cases for some tests - can you spot them ;) ?

**Comment by julianghionoiu** [comment]
There are missing step definitions and Cucumber is ignoring the Queue tests.
I have pushed a commit to enable strict checking and now the tests are failing for the right reason.
https://app.codeship.com/projects/163364/builds/38026706?pipeline=d7de54f6-d5d2-4d14-bdf3-2a0763868cfc

To answer your questions about the lack of "And" support in NodeJs.
The "And" keyword is a syntactic sugar and will match any other keywords, so "Given" can be used instead to implement it. See the other tests:

**Pull request merged**
